services:
  mkcosmetics:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mkcosmetics
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=3001
      - DB_PATH=/app/data/mkcosmetics.db
      - STATIC_DIR=/app/dist
      - TELEGRAM_CHANNEL=mkcosmetkor
    networks:
      - duda-shared

networks:
  duda-shared:
    external: true
