import { Product } from '../../core/types/product';

export const PRODUCTS_CATALOG: Product[] = [
  {
    id: 'cnp-pha-peeling-pad',
    name: 'CNP Rx Skin Rejuvenating PHA Peeling Pad (Set 60+5 pcs)',
    brand: 'CNP Rx (LG Group)',
    category: 'peeling-cleansing',
    skinConcerns: ['pores-acne', 'brightening', 'hydration'],
    description: 'Инновационные пилинг-пэды на основе PHA-кислот мягко отшелушивают ороговевшие клетки, очищают поры и стимулируют обновление кожи без раздражения. Идеально для чувствительной и проблемной кожи.',
    shortDescription: 'Деликатный пилинг с PHA-кислотами для гладкости и сияния кожи.',
    priceKrw: 23000,
    originalPriceKrw: 45000,
    images: [
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=800&q=80',
    ],
    volume: '60 шт + 5 шт (435 г)',
    rating: 4.9,
    reviewCount: 48,
    isBestseller: true,
    isNew: false,
    inStock: true,
    keyIngredients: ['PHA-кислоты (Глюконолактон)', 'Пантенол', 'Экстракт центеллы', 'Гиалуроновая кислота'],
    benefits: [
      'Мягкая эксфолиация без шелушений и покраснений',
      'Сужение пор и выравнивание микрорельефа',
      'Глубокое увлажнение и придание естественного сияния',
      'Подходит для ежедневного применения'
    ],
    howToUse: 'После умывания протрите лицо сначала рельефной стороной диска, затем гладкой. Не смывать.',
    telegramPostUrl: 'https://t.me/mkcosmetkor/12398',
  },
  {
    id: 'whoo-cheongidan-set',
    name: 'The History of Whoo Cheongidan Radiant Rejuvenating 6-Piece Set',
    brand: 'The History of Whoo',
    category: 'premium-luxury',
    skinConcerns: ['anti-age', 'lifting', 'brightening'],
    description: 'Императорский антивозрастной набор на основе секретных рецептов корейского королевского двора. Содержит 30 ценных восточных трав, дикий женьшень и 24K золото для восстановления упругости и сияния.',
    shortDescription: 'Люксовый королевский уход для глубокого омоложения и упругости.',
    priceKrw: 195000,
    originalPriceKrw: 320000,
    images: [
      'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=800&q=80'
    ],
    volume: 'Тонер 150+25мл, Эмульсия 110+25мл, Эссенция 8мл, Крем для век 5мл, Крем 10мл',
    rating: 5.0,
    reviewCount: 64,
    isBestseller: true,
    isNew: false,
    inStock: true,
    keyIngredients: ['Экстракт дикого женьшеня', 'Оленьи панты', 'Золото 24К', 'Комплекс CheonGiBiDan'],
    benefits: [
      'Мощный лифтинг-эффект и укрепление контура лица',
      'Разглаживание глубоких и мимических морщин',
      'Королевское сияние и устранение тусклости кожи'
    ],
    howToUse: 'Использовать по порядку: Тонер -> Эссенция -> Эмульсия -> Крем для век -> Крем для лица.',
    telegramPostUrl: 'https://t.me/mkcosmetkor/12395',
  },
  {
    id: 'sulwhasoo-first-care-serum',
    name: 'Sulwhasoo First Care Activating Serum VI (6th Gen, 90ml)',
    brand: 'Sulwhasoo',
    category: 'hydration-serums',
    skinConcerns: ['hydration', 'anti-age', 'brightening'],
    description: 'Культовая активирующая сыворотка первого шага с запатентованным комплексом Sulwhasoo Master Complex™. Мгновенно пробуждает кожу после очищения и ускоряет проникновение всех последующих уходовых средств.',
    shortDescription: 'Легендарная сыворотка первого шага для глубокого клеточного баланса.',
    priceKrw: 89000,
    originalPriceKrw: 140000,
    images: [
      'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80'
    ],
    volume: '90 мл',
    rating: 4.9,
    reviewCount: 112,
    isBestseller: true,
    isNew: false,
    inStock: true,
    keyIngredients: ['Sulwhasoo Master Complex™', 'Экстракт женьшеня', 'Пион', 'Лотос'],
    benefits: [
      'Активирует естественные процессы регенерации кожи',
      'Увеличивает эффективность последующего ухода в 3 раза',
      'Устраняет чувство стянутости после умывания'
    ],
    howToUse: 'Наносите 2-3 помпы на очищенное лицо сразу после умывания перед тонером.',
    telegramPostUrl: 'https://t.me/mkcosmetkor/12390',
  },
  {
    id: 'medi-peel-bor-tox-kit',
    name: 'Medi-Peel Bor-Tox 5 Peptide Multi Care Kit',
    brand: 'Medi-Peel',
    category: 'sets',
    skinConcerns: ['anti-age', 'lifting'],
    description: 'Комплекс средств с французским волюфилином 5% и 5 пептидами. Работает как безопасная безинъекционная альтернатива ботоксу, расслабляет мимические мышцы и заполняет морщины.',
    shortDescription: 'Пептидный ботокс-комплекс для лифтинга и заполнения морщин.',
    priceKrw: 38000,
    originalPriceKrw: 75000,
    images: [
      'https://images.unsplash.com/photo-1608248597359-00f7247a82c6?auto=format&fit=crop&w=800&q=80'
    ],
    volume: 'Тонер 30мл, Эмульсия 30мл, Сыворотка 30мл, Крем 50г',
    rating: 4.8,
    reviewCount: 39,
    isBestseller: false,
    isNew: true,
    inStock: true,
    keyIngredients: ['Volufiline 5% (Франция)', 'Комплекс 5 пептидов', 'Гидролизованный коллаген', 'Эластин'],
    benefits: [
      'Повышает плотность и упругость кожи',
      'Разглаживает заломы на лбу и носогубные складки',
      'Интенсивно питает и восстанавливает липидный барьер'
    ],
    howToUse: 'Используйте утром и вечером в последовательности: Тонер -> Сыворотка -> Эмульсия -> Крем.',
    telegramPostUrl: 'https://t.me/mkcosmetkor/12385',
  },
  {
    id: 'manyo-bifida-biome-ampoule',
    name: 'Manyo Factory Bifida Biome Complex Ampoule (50ml)',
    brand: 'Manyo Factory',
    category: 'hydration-serums',
    skinConcerns: ['sensitive', 'hydration', 'anti-age'],
    description: 'Бестселлер для укрепления защитного барьера с комплексом бифидо- и лактобактерий. Успокаивает раздражения, улучшает тургор и микрорельеф, защищает от негативных факторов внешней среды.',
    shortDescription: 'Сыворотка с пробиотиками для восстановления микробиома и защиты.',
    priceKrw: 24000,
    originalPriceKrw: 39000,
    images: [
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80'
    ],
    volume: '50 мл',
    rating: 4.9,
    reviewCount: 76,
    isBestseller: true,
    isNew: false,
    inStock: true,
    keyIngredients: ['Bifida Biome™ (Бифидобактерии)', '10 видов гиалуроновой кислоты', 'Пептидный комплекс'],
    benefits: [
      'Мгновенно снимает раздражение и покраснения',
      'Укрепляет иммунитет кожи',
      'Придает гладкость и здоровое сияние'
    ],
    howToUse: 'Наносите 2-4 капли на тонизированную кожу мягкими похлопывающими движениями.',
    telegramPostUrl: 'https://t.me/mkcosmetkor/12380',
  },
  {
    id: 'round-lab-birch-sun-cream',
    name: 'Round Lab Birch Juice Moisturizing Sunscreen SPF50+ PA++++ (50ml)',
    brand: 'Round Lab',
    category: 'sun-care',
    skinConcerns: ['hydration', 'sensitive'],
    description: 'Номер 1 солнцезащитный крем в Корее по версии Hwahae и Olive Young. Увлажняет кожу как легкий крем-эссенция, надежно защищает от UVA/UVB лучей, не белит и не оставляет жирного блеска.',
    shortDescription: 'Увлажняющий солнцезащитный крем №1 в Корее с березовым соком.',
    priceKrw: 17500,
    originalPriceKrw: 28000,
    images: [
      'https://images.unsplash.com/photo-1556228722-d9b3be647614?auto=format&fit=crop&w=800&q=80'
    ],
    volume: '50 мл',
    rating: 5.0,
    reviewCount: 95,
    isBestseller: true,
    isNew: false,
    inStock: true,
    keyIngredients: ['Березовый сок Индже', 'Гиалуроновая кислота', 'Ниацинамид', 'Химические фильтры нового поколения'],
    benefits: [
      'Высочайшая фотостабильная защита SPF50+ PA++++',
      'Легчайшая текстура эссенции без белых следов',
      'Увлажнение и свежесть на весь день'
    ],
    howToUse: 'Наносите завершающим этапом ухода за 15-20 минут до выхода на улицу.',
    telegramPostUrl: 'https://t.me/mkcosmetkor/12375',
  },
  {
    id: 'anua-heartleaf-77-toner',
    name: 'Anua Heartleaf 77% Soothing Toner (250ml)',
    brand: 'Anua',
    category: 'peeling-cleansing',
    skinConcerns: ['sensitive', 'pores-acne', 'hydration'],
    description: 'Успокаивающий тонер на 77% состоящий из экстракта хауттюйнии сердцевидной. Моментально снимает воспаления, снижает чувствительность, нормализует выработку кожного себума.',
    shortDescription: 'Культовый успокаивающий тонер с 77% экстракта хауттюйнии.',
    priceKrw: 19000,
    originalPriceKrw: 32000,
    images: [
      'https://images.unsplash.com/photo-1617897903246-719242758050?auto=format&fit=crop&w=800&q=80'
    ],
    volume: '250 мл',
    rating: 4.8,
    reviewCount: 52,
    isBestseller: true,
    isNew: false,
    inStock: true,
    keyIngredients: ['Экстракт хауттюйнии 77%', 'Экстракт центеллы', 'Пантенол', 'Экстракт ромашки'],
    benefits: [
      'Успокаивает акне и покраснения',
      'Восстанавливает оптимальный pH баланс 5.5-6',
      'Освежает и глубоко увлажняет'
    ],
    howToUse: 'Нанесите на ватный диск или ладони и аккуратно распределите по коже.',
  },
  {
    id: 'beauty-of-joseon-glow-serum',
    name: 'Beauty of Joseon Glow Serum: Propolis + Niacinamide (30ml)',
    brand: 'Beauty of Joseon',
    category: 'hydration-serums',
    skinConcerns: ['pores-acne', 'brightening', 'hydration'],
    description: 'Сыворотка с 60% экстракта прополиса и 2% ниацинамида создана для борьбы с воспалениями, сужения пор и придания коже роскошного медового сияния (glass skin).',
    shortDescription: 'Медовая сыворотка с прополисом и ниацинамидом для эффекта Glass Skin.',
    priceKrw: 16000,
    originalPriceKrw: 24000,
    images: [
      'https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?auto=format&fit=crop&w=800&q=80'
    ],
    volume: '30 мл',
    rating: 4.9,
    reviewCount: 88,
    isBestseller: true,
    isNew: false,
    inStock: true,
    keyIngredients: ['Экстракт прополиса 60%', 'Ниацинамид 2%', 'Масло таману', 'Салициловая кислота 0.5% (BHA)'],
    benefits: [
      'Антибактериальный и противовоспалительный эффект',
      'Осветление постакне и выравнивание тона',
      'Эффект здорового корейского сияния кожи'
    ],
    howToUse: 'Нанесите 2-3 капли на лицо после тонера и мягко вмассируйте.',
  }
];
